services:
  mariadb:
    image: mariadb
    container_name: mariadbPF
    environment:
      - PUID=1000
      - PGID=1000
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DB}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_USER_PASS}
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadminPF
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8081:80
    depends_on:
      - mariadb
  clientemqtt:
    build:
      context: ./clienteMqtt    # ruta donde está el Dockerfile y el script Python
      dockerfile: Dockerfile    # nombre del Dockerfile (opcional si se llama Dockerfile)
    image: clientemqtt
    container_name: clientemqttPF
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - SERVIDOR=${SERVIDOR} #Se reemplazará por la env var SERVIDOR defineda en .env
      - TOPICO1=${TOPICO1}
      - TOPICO2=${TOPICO2}
      - MARIADB_SERVER=${MARIADB_SERVER}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_USER_PASS=${MARIADB_USER_PASS}
      - MARIADB_DB=${MARIADB_DB}
      - MQTT_USR=${MQTT_USR}
      - MQTT_PASS=${MQTT_PASS}
      - PUERTO_MQTTS=${PUERTO_MQTTS}
    restart: unless-stopped
    depends_on:
      - mariadb
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquittoPF
    user: "1000:1000"
    ports:
      - 1883:1883
    restart: unless-stopped
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  
  crud:
    build:
      context: ./crud    # ruta donde está el Dockerfile y el script Python
      dockerfile: Dockerfile
    image: crud
    container_name: crudPF
    environment:
      - MYSQL_USER=${CRUD_USER}
      - MYSQL_PASSWORD=${CRUD_PASS}
      - MYSQL_DB=${CRUD_DB}
      - MYSQL_HOST=${MARIADB_SERVER}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - mariadb
